export const SET_HANDLE_NOTIFICATION_LOGIN = 'SET_HANDLE_NOTIFICATION_LOGIN';
export const SET_HANDLE_LOGIN_ERROR = 'SET_HANDLE_LOGIN_ERROR';
export const SET_HANDLE_GET_USERS_ERROR = 'SET_HANDLE_GET_USERS_ERROR';
export const SET_HANDLE_POST_USER_ERROR = 'SET_HANDLE_POST_USER_ERROR';
export const SET_HANDLE_PUT_USER_ERROR = 'SET_HANDLE_PUT_USER_ERROR';
export const SET_HANDLE_DELETE_USER_ERROR = 'SET_HANDLE_DELETE_USER_ERROR'; 