export const SET_HANDLE_LASTUSERIDSET_HANDLE_LOGIN = 'SET_HANDLE_LOGIN';
export const SET_HANDLE_LASTUSERID = 'SET_HANDLE_LASTUSERID'
export const SET_HANDLE_LOGIN = 'SET_HANDLE_LOGIN';
export const SET_HANDLE_LASTPATIENTID = 'SET_HANDLE_LASTPATIENTID'
